export {ReactComponent as BackIcon} from './components/images/icons/backicon.svg';
export {ReactComponent as EmailIcon} from './components/images/icons/email.svg';
export {ReactComponent as SMSIcon} from './components/images/icons/sms.svg';
export {ReactComponent as WhatsAppIcon} from './components/images/icons/whatsapp.svg';
export {ReactComponent as ShopifyTagIcon } from './components/images/icons/shopifytag.svg';
export {ReactComponent as VeirfyTagIcon} from './components/images/icons/verifyorderunicommerece.svg';
export {ReactComponent as OrderOnShopifyIcon} from './components/images/icons/orderonshopify.svg';
export {ReactComponent as DiscountsIcon} from './components/images/icons/discount.svg';
export {ReactComponent as PaymentsLinkIcon} from './components/images/icons/paymentlink.svg';
export {ReactComponent as TimeDelayIcon} from './components/images/icons/timer.svg';
export {ReactComponent as SplitIcon} from './components/images/icons/split.svg';
export {ReactComponent as ThunderIcon} from './components/images/icons/thunder.svg';
export { ReactComponent as SnackbarCloseIcon } from './components/images/icons/close-icon.svg';
export {ReactComponent as DownArrow16} from './components/images/icons/down-arrow-16.svg';